handlers = java.util.logging.FileHandler, java.util.logging.ConsoleHandler

java.util.logging.FileHandler.level = ALL
java.util.logging.FileHandler.pattern = /storage/yamcs-logs/yamcs-server.log
java.util.logging.FileHandler.limit = 20000000
java.util.logging.FileHandler.count = 1000
java.util.logging.FileHandler.formatter = org.yamcs.logging.CompactFormatter

java.util.logging.ConsoleHandler.level = INFO
java.util.logging.ConsoleHandler.formatter = org.yamcs.logging.ConsoleFormatter

org.yamcs.level = INFO
com.jaops.yaoki.level = FINE


#this will cause the events to be also logged
org.yamcs.events.EventProducer.level = ALL

